apiVersion: v1
kind: Namespace
metadata:
  name: finserv-ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anf-data-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${ANF_DATA_IP}
    path: /${ANF_DATA_VOL}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anf-data-pvc
  namespace: finserv-ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anf-milvus-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${ANF_MILVUS_IP}
    path: /${ANF_MILVUS_VOL}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anf-milvus-pvc
  namespace: finserv-ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
